/*
@HSHELL_ACCESSIBILITYSTATE 11
@HSHELL_ACTIVATESHELLWINDOW 3
@HSHELL_APPCOMMAND 12
@HSHELL_ENDTASK 10
@HSHELL_FLASH ( HSHELL_REDRAW | HSHELL_HIGHBIT )
@HSHELL_GETMINRECT 5
@HSHELL_HIGHBIT 0x8000
@HSHELL_LANGUAGE 8
@HSHELL_MONITORCHANGED 16
@HSHELL_REDRAW 6
@HSHELL_RUDEAPPACTIVATED ( HSHELL_WINDOWACTIVATED | HSHELL_HIGHBIT )
@HSHELL_SYSMENU 9
@HSHELL_TASKMAN 7
@HSHELL_WINDOWACTIVATED 4
@HSHELL_WINDOWCREATED 1
@HSHELL_WINDOWDESTROYED 2
@HSHELL_WINDOWREPLACED 13
@HSHELL_WINDOWREPLACING 14
*/
RegisterShellHookCallback(function, maxThreads := 1) {
    OnMessage(DllCall("RegisterWindowMessage", "str", "ShellHook"), function, maxThreads)
    if maxThreads
        return DllCall("RegisterShellHookWindow", "ptr", A_ScriptHwnd)
}

UnRegisterShellHook() => DllCall("DeregisterShellHookWindow", "ptr", A_ScriptHwnd)